import type { Metadata } from "next";
import { Nunito_Sans, DM_Serif_Display, Oooh_Baby } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/Footer/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Script from "next/script";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-nunito",
});
const dm = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dm",
});
const baby = Oooh_Baby({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-baby",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://adaired.com"),
  title: "Adaired Digital Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <meta
          name="google-site-verification"
          content="IbErkjWfX4xDEzZjtgtMruxBWkCYRs6n19e55PaEtLw"
        />
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-5ZWYZ5BF47"
        />
        <Script id="google-analytics">
          {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-5ZWYZ5BF47');
  `}
        </Script>
      </head>
      <body
        id="root"
        className={cn(
          "relative h-full antialiased",
          dm.variable,
          nunito.variable,
          baby.variable
        )}
      >
        <main>
          <Navbar />
          {children}
          <Footer />
        </main>
        <Toaster />
        <SpeedInsights />
      </body>
    </html>
  );
}
