import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "../globals.css";
import MainWebLayout from "./weblayout/MainWebLayout";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${montserrat.variable} ${poppins.variable}`}>
      <body className="antialiased suppressHydrationWarning">
        <MainWebLayout>{children}</MainWebLayout>
      </body>
    </html>
  );
}
